{
 "title": "Home Internet Speed",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "server_name",
    "label": "Server name",
    "query": {
     "query": "label_values(speedtest_ping_latency,server_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Download Speed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(speedtest_download_bandwidth{server_name=\"$server_name\"}) by (server_name) * 8",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "Upload Speed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(speedtest_upload_bandwidth{server_name=\"$server_name\"}) by (server_name) * 8",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "Ping Latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(speedtest_ping_latency{server_name=\"$server_name\"}) by (server_name)",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "Download Latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(speedtest_download_latency{server_name=\"$server_name\"}) by (server_name)",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "Upload Latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(speedtest_upload_latency{server_name=\"$server_name\"}) by (server_name)",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "Packet Loss",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(speedtest_packet_loss{server_name=\"$server_name\"}) by (server_name)",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "Download speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(speedtest_download_bandwidth{server_name=\"$server_name\"}) by (server_name) * 8",
     "legendFormat": "{{server_name}} -> {{isp}}"
    },
    {
     "expr": "sum(speedtest_download_bandwidth) * 8",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Upload speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(speedtest_upload_bandwidth{server_name=\"$server_name\"}) by (server_name) * 8",
     "legendFormat": "{{isp}} -> {{server_name}}"
    },
    {
     "expr": "sum(speedtest_upload_bandwidth) * 8",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Download Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(speedtest_download_latency{server_name=\"$server_name\"}) by (server_name)",
     "legendFormat": "Download - {{server_name}}"
    },
    {
     "expr": "sum(speedtest_download_latency)",
     "legendFormat": "Download - All"
    }
   ]
  },
  {
   "title": "Upload Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(speedtest_upload_latency{server_name=\"$server_name\"}) by (server_name)",
     "legendFormat": "Upload - {{server_name}}"
    },
    { "expr": "sum(speedtest_upload_latency)", "legendFormat": "Upload - All" }
   ]
  },
  {
   "title": "Ping Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(speedtest_ping_latency{server_name=\"$server_name\"}) by (server_name)",
     "legendFormat": "Ping - {{server_name}}"
    },
    { "expr": "sum(speedtest_ping_latency)", "legendFormat": "Ping - All" }
   ]
  }
 ]
}